### ISSUE TITLE
Translated version?

### ISSUE THREAD

**Issue by DeepDiver1975** [GenestealerCult/DatacardApp#1]
Is it possible to translate the data cards?
I'd like to have them in German

Happy to help out with development!

Thanks a lot

**Comment by GenestealerCult** [comment]
All text is read from the Battle Scribe roster file, so the translation should already be done there. Have you checked if it is possible to get a German roster file from Battle Scribe? I'd love to hear if it works, or what problems there are with it.

**Comment by DeepDiver1975** [comment]
> All text is read from the Battle Scribe roster file, so the translation should already be done there. Have you checked if it is possible to get a German roster file from Battle Scribe? I'd love to hear if it works, or what problems there are with it.

THX a lot - I'll double check this asap. :+1:

**Comment by DeepDiver1975** [comment]
Looks like BattleScribe doesn't have translations .... :shrug:
